```{r}
rm(list = ls())
options(warn=-1)
library(rgl)
library(misc3d)

# 设置 WebGL
options(rgl.printRglwidget = TRUE)
setupKnitr()  # 如果在 RMarkdown 中使用
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

```

```{r}
source("/home/xmabs/MATH5472/STitch3D_no_batch_effect/plot3D_func.R")

```

```{r}
celltypes <- c("salivary.gland")
celltype_colors <- c("#7f7f7f")
um <- c(0.9776033, -0.2083614, 0.02960751, 0,
        -0.1809667, -0.9040827, -0.38715008, 0,
        0.1074345, 0.3731217, -0.92154104, 0,
        0, 0, 0, 1) #set the initial view of the 3D plot
spot_radius <- 0.5
axis_rescale <- c(1, 1, 1.5)
alpha_threshold <- 0.5
alpha_background <- 0.02

# 使用 open3d() 创建新的3D窗口
open3d()


plot3D_proportions(directory = "/home/xmabs/MATH5472/STitch3D_no_batch_effect/results_Drosophila_embryo",
                   celltypes = celltypes,
                   celltype_colors = celltype_colors,
                   um = um,
                   spot_radius = spot_radius,
                   alpha_threshold = alpha_threshold,
                   alpha_background = alpha_background
                   )

# 添加坐标轴和标签
box3d()
axis3d("x-+")
axis3d("y-+")
axis3d("z-+")
title3d(xlab = "x", ylab = "y")
mtext3d("z", "z-+", line = 4)

# 使用 rglwidget() 在RMarkdown中显示交互式3D图形
rglwidget()

```